version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    image: fastapi
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongo
      - mongo_express
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db  # corrected this line
  mongo_express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_MONGODB_URL}
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
